#!/usr/bin/env python3
"""Static setup catalog and fixtures for the local AI helper."""

from __future__ import annotations

import local_ai_routing
from local_ai_support.setup_constants import (
    EMBEDDING_PROFILE,
    MAX_DAILY_INPUT_BYTES,
    TEXT_TASK_PROFILE,
    VISION_PROFILE,
)

DAILY_TEXT_TASKS = {
    "validation-triage",
    "code-review",
    "implementation-planning",
    "patch-draft",
    "inventory-summary",
    "changelog-draft",
    "changed-files-summary",
    "failure-cluster",
    "test-gap-summary",
    "handoff-draft",
    "duplicate-overlap-detection",
}
LOCAL_AI_COMMAND_PREFIX = "python -B .agents/manage.py local-ai"
LOCAL_AI_METADATA_FIELDS = {"id", "command", "applies_when", "guardrail", "evidence_input", "owner"}

MODEL_PACKAGES = [
    {
        "profile": "nemotron3-nano4b",
        "aliases": ["nemotron-3-nano-4b-q4"],
        "kind": "text",
        "tier": "primary",
        "default_install": True,
        "repo": "nvidia/NVIDIA-Nemotron-3-Nano-4B-GGUF",
        "base_model": "nvidia/NVIDIA-Nemotron-3-Nano-4B",
        "license_repo": "nvidia/NVIDIA-Nemotron-3-Nano-4B-GGUF",
        "revision": "main",
        "license_revision": "main",
        "license_url": "https://www.nvidia.com/en-us/agreements/enterprise-software/nvidia-nemotron-open-model-license/",
        "license_artifact": "NVIDIA-Nemotron-Open-Model-License.html",
        "file": "NVIDIA-Nemotron3-Nano-4B-Q4_K_M.gguf",
        "quant": "Q4_K_M",
        "license": "NVIDIA Open Model License",
        "roles": ["routing", "summary", "triage", "inventory", "json", "review", "planning", "draft"],
        "context_tokens": 4096,
        "output_tokens": 192,
        "expected_size_gb": 2.64,
        "purpose": "Primary CPU profile for repo-local routing, summaries, tool/navigation triage, planning, and draft review tasks.",
    },
    {
        "profile": "qwen3-embedding-4b",
        "aliases": ["qwen3-embedding-4b-q4"],
        "kind": "embedding",
        "tier": "optional-embedding",
        "default_install": False,
        "repo": "Qwen/Qwen3-Embedding-4B-GGUF",
        "base_model": "Qwen/Qwen3-Embedding-4B",
        "license_repo": "Qwen/Qwen3-Embedding-4B",
        "revision": "main",
        "license_revision": "main",
        "license_url": "https://www.apache.org/licenses/LICENSE-2.0.txt",
        "file": "Qwen3-Embedding-4B-Q4_K_M.gguf",
        "quant": "Q4_K_M",
        "license": "Apache-2.0",
        "roles": ["embedding", "benchmark"],
        "context_tokens": 4096,
        "output_tokens": 0,
        "expected_size_gb": 2.33,
        "purpose": "Optional semantic-retrieval benchmark profile for larger or messier extracted repository and document text corpora.",
    },
    {
        "profile": "qwen3-embedding-0.6b-q8",
        "aliases": ["qwen3-embedding-0.6b"],
        "kind": "embedding",
        "tier": "optional-embedding",
        "default_install": False,
        "repo": "Qwen/Qwen3-Embedding-0.6B-GGUF",
        "base_model": "Qwen/Qwen3-Embedding-0.6B",
        "license_repo": "Qwen/Qwen3-Embedding-0.6B",
        "revision": "main",
        "license_revision": "main",
        "license_url": "https://www.apache.org/licenses/LICENSE-2.0.txt",
        "file": "Qwen3-Embedding-0.6B-Q8_0.gguf",
        "quant": "Q8_0",
        "license": "Apache-2.0",
        "roles": ["embedding", "benchmark"],
        "context_tokens": 4096,
        "output_tokens": 0,
        "expected_size_gb": 0.63,
        "purpose": "Optional smaller embedding profile for explicit embedding benchmarks and low-memory installs.",
    },
    {
        "profile": "qwen3-embedding-4b-q5km",
        "aliases": ["qwen3-embedding-4b-q5"],
        "kind": "embedding",
        "tier": "optional-embedding",
        "default_install": False,
        "repo": "Qwen/Qwen3-Embedding-4B-GGUF",
        "base_model": "Qwen/Qwen3-Embedding-4B",
        "license_repo": "Qwen/Qwen3-Embedding-4B",
        "revision": "main",
        "license_revision": "main",
        "license_url": "https://www.apache.org/licenses/LICENSE-2.0.txt",
        "file": "Qwen3-Embedding-4B-Q5_K_M.gguf",
        "quant": "Q5_K_M",
        "license": "Apache-2.0",
        "roles": ["embedding", "benchmark"],
        "context_tokens": 4096,
        "output_tokens": 0,
        "expected_size_gb": 2.69,
        "purpose": "Optional higher-precision 4B embedding benchmark candidate.",
    },
    {
        "profile": "qwen3-embedding-8b-q4km",
        "aliases": ["qwen3-embedding-8b-q4"],
        "kind": "embedding",
        "tier": "optional-embedding",
        "default_install": False,
        "repo": "Qwen/Qwen3-Embedding-8B-GGUF",
        "base_model": "Qwen/Qwen3-Embedding-8B",
        "license_repo": "Qwen/Qwen3-Embedding-8B",
        "revision": "main",
        "license_revision": "main",
        "license_url": "https://www.apache.org/licenses/LICENSE-2.0.txt",
        "file": "Qwen3-Embedding-8B-Q4_K_M.gguf",
        "quant": "Q4_K_M",
        "license": "Apache-2.0",
        "roles": ["embedding", "benchmark"],
        "context_tokens": 4096,
        "output_tokens": 0,
        "expected_size_gb": 4.36,
        "purpose": "Optional larger embedding benchmark candidate; promote only if retrieval quality improves enough to justify latency and storage.",
    },
    {
        "profile": "qwen3vl-2b-q4",
        "aliases": ["qwen3-vl-2b-q4"],
        "kind": "vision",
        "tier": "vision",
        "default_install": True,
        "repo": "Qwen/Qwen3-VL-2B-Instruct-GGUF",
        "base_model": "Qwen/Qwen3-VL-2B-Instruct",
        "license_repo": "Qwen/Qwen3-VL-2B-Instruct",
        "revision": "main",
        "license_revision": "main",
        "license_url": "https://www.apache.org/licenses/LICENSE-2.0.txt",
        "file": "Qwen3VL-2B-Instruct-Q4_K_M.gguf",
        "mmproj_file": "mmproj-Qwen3VL-2B-Instruct-Q8_0.gguf",
        "mmproj_url": "https://huggingface.co/Qwen/Qwen3-VL-2B-Instruct-GGUF/resolve/main/mmproj-Qwen3VL-2B-Instruct-Q8_0.gguf",
        "quant": "Q4_K_M",
        "license": "Apache-2.0",
        "roles": ["vision", "image-description", "jpeg", "png"],
        "context_tokens": 2048,
        "output_tokens": 160,
        "expected_size_gb": 1.45,
        "purpose": "Default local vision model for JPEG/PNG image descriptions through llama-mtmd-cli.",
    },
]

RUNTIME_PACKAGES = [
    {
        "backend": "cpu",
        "platform": "windows-x64",
        "label": "llama-b9222-win-cpu-x64",
        "url": "https://github.com/ggml-org/llama.cpp/releases/download/b9222/llama-b9222-bin-win-cpu-x64.zip",
        "archive": "llama-b9222-bin-win-cpu-x64.zip",
        "folder": "llama-b9222-win-cpu-x64",
    },
    {
        "backend": "cpu",
        "platform": "windows-x64",
        "label": "llama-b9219-win-cpu-x64",
        "url": "https://github.com/ggml-org/llama.cpp/releases/download/b9219/llama-b9219-bin-win-cpu-x64.zip",
        "archive": "llama-b9219-bin-win-cpu-x64.zip",
        "folder": "llama-b9219-win-cpu-x64",
    },
    {
        "backend": "cpu",
        "platform": "windows-x64",
        "label": "llama-b9131-win-cpu-x64",
        "url": "https://github.com/ggml-org/llama.cpp/releases/download/b9131/llama-b9131-bin-win-cpu-x64.zip",
        "archive": "llama-b9131-bin-win-cpu-x64.zip",
        "folder": "llama-b9131-win-cpu-x64",
    },
]

GPU_RUNTIME_PACKAGES = [
    {
        "backend": "cuda",
        "platform": "windows-x64",
        "label": "llama-b9222-win-cuda-12.4-x64",
        "url": "https://github.com/ggml-org/llama.cpp/releases/download/b9222/llama-b9222-bin-win-cuda-12.4-x64.zip",
        "archive": "llama-b9222-bin-win-cuda-12.4-x64.zip",
        "folder": "llama-b9222-win-cuda-12.4-x64",
        "dependencies": [
            {
                "url": "https://github.com/ggml-org/llama.cpp/releases/download/b9222/cudart-llama-bin-win-cuda-12.4-x64.zip",
                "archive": "cudart-llama-bin-win-cuda-12.4-x64.zip",
            }
        ],
        "auto": True,
    },
    {
        "backend": "vulkan",
        "platform": "windows-x64",
        "label": "llama-b9222-win-vulkan-x64",
        "url": "https://github.com/ggml-org/llama.cpp/releases/download/b9222/llama-b9222-bin-win-vulkan-x64.zip",
        "archive": "llama-b9222-bin-win-vulkan-x64.zip",
        "folder": "llama-b9222-win-vulkan-x64",
        "auto": True,
    },
    {
        "backend": "hip",
        "platform": "windows-x64",
        "label": "llama-b9222-win-hip-radeon-x64",
        "url": "https://github.com/ggml-org/llama.cpp/releases/download/b9222/llama-b9222-bin-win-hip-radeon-x64.zip",
        "archive": "llama-b9222-bin-win-hip-radeon-x64.zip",
        "folder": "llama-b9222-win-hip-radeon-x64",
        "auto": False,
    },
    {
        "backend": "sycl",
        "platform": "windows-x64",
        "label": "llama-b9222-win-sycl-x64",
        "url": "https://github.com/ggml-org/llama.cpp/releases/download/b9222/llama-b9222-bin-win-sycl-x64.zip",
        "archive": "llama-b9222-bin-win-sycl-x64.zip",
        "folder": "llama-b9222-win-sycl-x64",
        "auto": False,
    },
    {
        "backend": "opencl",
        "platform": "windows-arm64",
        "label": "llama-b9222-win-opencl-adreno-arm64",
        "url": "https://github.com/ggml-org/llama.cpp/releases/download/b9222/llama-b9222-bin-win-opencl-adreno-arm64.zip",
        "archive": "llama-b9222-bin-win-opencl-adreno-arm64.zip",
        "folder": "llama-b9222-win-opencl-adreno-arm64",
        "auto": False,
    },
]

DEFAULT_CONFIG = {
    "enabled": True,
    "mode": "auto",
    "tasks": list(
        dict.fromkeys(
            [
                *local_ai_routing.DEFAULT_TASK_MODEL_PROFILES.keys(),
                *local_ai_routing.DEFAULT_TASK_ENVELOPES.keys(),
            ]
        )
    ),
    "backend_order": ["auto", "cpu"],
    "active_profile": local_ai_routing.DEFAULT_MODEL_PROFILE,
    "primary_profiles": local_ai_routing.DEFAULT_PRIMARY_PROFILES,
    "optional_profiles": local_ai_routing.DEFAULT_OPTIONAL_PROFILES,
    "embedding_profiles": local_ai_routing.DEFAULT_EMBEDDING_PROFILES,
    "vision_profiles": local_ai_routing.DEFAULT_VISION_PROFILES,
    "image_description_profile": local_ai_routing.DEFAULT_IMAGE_DESCRIPTION_PROFILE,
    "model_profiles": local_ai_routing.DEFAULT_MODEL_PROFILES,
    "task_model_profiles": local_ai_routing.DEFAULT_TASK_MODEL_PROFILES,
    "task_envelopes": local_ai_routing.DEFAULT_TASK_ENVELOPES,
    "model_task_envelopes": local_ai_routing.DEFAULT_MODEL_TASK_ENVELOPES,
    "task_attempt_policy": local_ai_routing.DEFAULT_TASK_ATTEMPT_POLICY,
    "benchmark_policy": local_ai_routing.DEFAULT_BENCHMARK_POLICY,
    "model_catalog": local_ai_routing.DEFAULT_MODEL_CATALOG,
    "bootstrap": {
        "auto_config": True,
        "auto_download": "on-local-ai-use",
        "direct_script_fallback": True,
        "default_profiles": [
            str(item["profile"]) for item in MODEL_PACKAGES if item.get("default_install")
        ],
        "max_download_gb": 20,
    },
    "limits": {
        "threads": 8,
        "threads_batch": 8,
        "context_tokens": 4096,
        "output_tokens": 256,
        "batch_size": 512,
        "ubatch_size": 256,
        "timeout_seconds": 300,
        "confidence_threshold": 0.7,
        "max_text_chars": 180,
    },
    "server": local_ai_routing.DEFAULT_SERVER_CONFIG,
    "tools": local_ai_routing.DEFAULT_TOOLS_CONFIG,
    "bundle_manifest": ".agents/local-ai/bundle/manifest.json",
    "cache_dir": ".agents/local-ai/cache",
}

BENCH_FIXTURES = [
    {
        "task": "skill-routing",
        "item": {
            "id": "bench-skill-routing",
            "name": "route-mapping-helper",
            "category": "General",
            "description": "Create and validate generated route mappings for repository skills.",
            "source_paths": [".agents/skills/skill-manager/SKILL.md"],
        },
        "allowed_categories": ["General", "AI Agents", "Documentation"],
    },
    {
        "task": "workflow-routing",
        "item": {
            "id": "bench-workflow-routing",
            "name": "story-flow",
            "summary": "Automate story implementation from intake through validation and generated routing.",
            "related_skills": ["skill-manager", "workflow-manager"],
            "scripts": [".agents/manage.py check"],
            "outputs": ["runs/<run-id>/run.json", "runs/<run-id>/REPORT.md"],
        },
        "allowed_categories": ["General"],
    },
]

EMBEDDING_BENCH_TEXTS = [
    "Local AI setup policy and deterministic fallback behavior.",
    "Skill routing maps are generated artifacts and must not be edited by hand.",
    "Validation triage should cite fresh command output before suggesting fixes.",
    "Repository search should return grounded paths and abstain when evidence is absent.",
]

INTEGRATION_SUGGESTIONS = [
    {
        "id": "skill-routing",
        "target": "skill",
        "task": "skill-routing",
        "manager": "skill-manager",
        "profile": TEXT_TASK_PROFILE,
        "command": "python -B .agents/manage.py sync-skill-routing",
        "suggestion": (
            "Use local AI only for generated skill routing suggestions after "
            "schema, hash, category, and confidence validation."
        ),
        "guardrail": "The model never edits skill source files; accepted output only changes generated routing artifacts.",
    },
    {
        "id": "skill-validation-triage",
        "target": "skill",
        "task": "validation-triage",
        "manager": "skill-manager",
        "profile": TEXT_TASK_PROFILE,
        "command": "python -B .agents/manage.py local-ai task --task validation-triage --input <file-or-->",
        "suggestion": (
            "Use bounded local summaries for validation failures, review packets, "
            "and candidate-skill improvement notes."
        ),
        "guardrail": "Treat output as review evidence; a normal agent or human applies edits.",
    },
    {
        "id": "skill-review-draft",
        "target": "skill",
        "task": "code-review",
        "manager": "skill-manager",
        "profile": TEXT_TASK_PROFILE,
        "command": "python -B .agents/manage.py local-ai task --task code-review --input <file>",
        "suggestion": "Use local AI for draft review notes over bounded local evidence.",
        "guardrail": "The helper only emits review-layer findings; source edits remain human or normal-agent controlled.",
    },
    {
        "id": "skill-patch-draft",
        "target": "skill",
        "task": "patch-draft",
        "manager": "skill-manager",
        "profile": TEXT_TASK_PROFILE,
        "command": "python -B .agents/manage.py local-ai task --task patch-draft --input <file>",
        "suggestion": "Use local AI for prose patch suggestions when a narrow fix area is already known.",
        "guardrail": "No apply/edit command exists; patch output is a draft suggestion only.",
    },
    {
        "id": "skill-changed-files-summary",
        "target": "skill",
        "task": "changed-files-summary",
        "manager": "skill-manager",
        "profile": TEXT_TASK_PROFILE,
        "command": "python -B .agents/manage.py local-ai task --task changed-files-summary --input <file-or-->",
        "suggestion": "Use local AI to summarize skill changed-file ownership, review focus, and handoff facts.",
        "guardrail": "Treat the summary as advisory; git diff and deterministic reports remain authoritative.",
    },
    {
        "id": "skill-failure-cluster",
        "target": "skill",
        "task": "failure-cluster",
        "manager": "skill-manager",
        "profile": TEXT_TASK_PROFILE,
        "command": "python -B .agents/manage.py local-ai task --task failure-cluster --input <file-or-->",
        "suggestion": "Use local AI to cluster skill validation logs by first failing fact and next deterministic check.",
        "guardrail": "Preserve command exit codes and rerun deterministic checks before claiming a fix.",
    },
    {
        "id": "skill-handoff-draft",
        "target": "skill",
        "task": "handoff-draft",
        "manager": "skill-manager",
        "profile": TEXT_TASK_PROFILE,
        "command": "python -B .agents/manage.py local-ai task --task handoff-draft --input <file-or-->",
        "suggestion": "Use local AI to draft concise skill handoff text from recorded evidence before normal agent verification.",
        "guardrail": "The normal agent must verify validation, skipped checks, and unsupported claims before finalizing.",
    },
    {
        "id": "skill-duplicate-overlap-detection",
        "target": "skill",
        "task": "duplicate-overlap-detection",
        "manager": "skill-manager",
        "profile": TEXT_TASK_PROFILE,
        "command": "python -B .agents/manage.py local-ai task --task duplicate-overlap-detection --input <file-or-->",
        "suggestion": "Use local AI to flag overlap between candidate behavior and accepted skill or workflow owners.",
        "guardrail": "Accepted owners and deterministic review decide merge, rewrite, split, or reject.",
    },
    {
        "id": "workflow-routing",
        "target": "workflow",
        "task": "workflow-routing",
        "manager": "workflow-manager",
        "profile": TEXT_TASK_PROFILE,
        "command": "python -B .agents/manage.py sync-automation-routing",
        "suggestion": (
            "Use local AI only for generated workflow routing summaries after "
            "schema, hash, length, and confidence validation."
        ),
        "guardrail": "The model never edits workflow source files; accepted output only changes generated routing artifacts.",
    },
    {
        "id": "workflow-validation-triage",
        "target": "workflow",
        "task": "validation-triage",
        "manager": "workflow-manager",
        "profile": TEXT_TASK_PROFILE,
        "command": "python -B .agents/manage.py local-ai task --task validation-triage --input <file-or-->",
        "suggestion": (
            "Use bounded local summaries for workflow validation failures, "
            "run ledgers, and follow-up evidence triage."
        ),
        "guardrail": "Use brokered read-only repo access and write only helper cache files.",
    },
    {
        "id": "workflow-changed-files-summary",
        "target": "workflow",
        "task": "changed-files-summary",
        "manager": "workflow-manager",
        "profile": TEXT_TASK_PROFILE,
        "command": "python -B .agents/manage.py local-ai task --task changed-files-summary --input <file-or-->",
        "suggestion": "Use local AI to summarize changed-file ownership, review focus, and handoff facts before paid-model final reporting.",
        "guardrail": "Treat the summary as advisory; git diff and changed-evidence packets remain authoritative.",
    },
    {
        "id": "workflow-failure-cluster",
        "target": "workflow",
        "task": "failure-cluster",
        "manager": "workflow-manager",
        "profile": TEXT_TASK_PROFILE,
        "command": "python -B .agents/manage.py local-ai task --task failure-cluster --input <file-or-->",
        "suggestion": "Use local AI to cluster validation logs by first failing fact and next deterministic check.",
        "guardrail": "Preserve command exit codes and rerun deterministic checks before claiming a fix.",
    },
    {
        "id": "workflow-test-gap-summary",
        "target": "workflow",
        "task": "test-gap-summary",
        "manager": "workflow-manager",
        "profile": TEXT_TASK_PROFILE,
        "command": "python -B .agents/manage.py local-ai task --task test-gap-summary --input <file-or-->",
        "suggestion": "Use local AI to summarize likely test gaps before paying for model-assisted test authoring.",
        "guardrail": "The helper does not write tests and cannot decide coverage sufficiency.",
    },
    {
        "id": "workflow-handoff-draft",
        "target": "workflow",
        "task": "handoff-draft",
        "manager": "workflow-manager",
        "profile": TEXT_TASK_PROFILE,
        "command": "python -B .agents/manage.py local-ai task --task handoff-draft --input <file-or-->",
        "suggestion": "Use local AI to draft concise handoff text from recorded evidence before normal agent verification.",
        "guardrail": "The normal agent must verify validation, skipped checks, and unsupported claims before finalizing.",
    },
    {
        "id": "workflow-duplicate-overlap-detection",
        "target": "workflow",
        "task": "duplicate-overlap-detection",
        "manager": "workflow-manager",
        "profile": TEXT_TASK_PROFILE,
        "command": "python -B .agents/manage.py local-ai task --task duplicate-overlap-detection --input <file-or-->",
        "suggestion": "Use local AI to flag overlap between candidate/reference behavior and accepted workflow or skill owners.",
        "guardrail": "Accepted owners and deterministic review decide merge, rewrite, split, or reject.",
    },
    {
        "id": "workflow-rendered-document-review",
        "target": "workflow",
        "task": "inventory-summary",
        "manager": "workflow-manager",
        "profile": VISION_PROFILE,
        "command": "python -B .agents/manage.py local-ai vision pdf --pdf <file> --pages 1-5",
        "suggestion": "Use rendered-page vision only when layout, raster text, screenshots, or inline images matter.",
        "guardrail": "PDF pages are rendered into the helper cache; source documents are never modified.",
    },
]
