// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TreadmillRunner.Infrastructure.Persistence;

#nullable disable

namespace TreadmillRunner.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TreadmillRunnerDbContext))]
    [Migration("20260804145850_AddOrderedWorkoutPrograms")]
    partial class AddOrderedWorkoutPrograms
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("TreadmillRunner.Infrastructure.Persistence.CalendarExceptionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CalendarSeriesId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("LocalDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CalendarSeriesId", "LocalDate")
                        .IsUnique();

                    b.ToTable("CalendarExceptions", (string)null);
                });

            modelBuilder.Entity("TreadmillRunner.Infrastructure.Persistence.CalendarExceptionOptionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CalendarExceptionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WorkoutRevisionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutRevisionId");

                    b.HasIndex("CalendarExceptionId", "DisplayOrder")
                        .IsUnique();

                    b.ToTable("CalendarExceptionOptions", (string)null);
                });

            modelBuilder.Entity("TreadmillRunner.Infrastructure.Persistence.CalendarSeriesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("IntervalWeeks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<int>("WeekdayMask")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("CalendarSeries", null, t =>
                        {
                            t.HasCheckConstraint("CK_CalendarSeries_DateRange", "\"EndDate\" IS NULL OR \"EndDate\" >= \"StartDate\"");

                            t.HasCheckConstraint("CK_CalendarSeries_Interval", "\"IntervalWeeks\" > 0");

                            t.HasCheckConstraint("CK_CalendarSeries_Version", "\"Version\" > 0");

                            t.HasCheckConstraint("CK_CalendarSeries_Weekdays", "\"WeekdayMask\" > 0 AND \"WeekdayMask\" <= 127");
                        });
                });

            modelBuilder.Entity("TreadmillRunner.Infrastructure.Persistence.CalendarSeriesOptionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CalendarSeriesId")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WorkoutRevisionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutRevisionId");

                    b.HasIndex("CalendarSeriesId", "DisplayOrder")
                        .IsUnique();

                    b.ToTable("CalendarSeriesOptions", (string)null);
                });

            modelBuilder.Entity("TreadmillRunner.Infrastructure.Persistence.DeviceEnrollmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ArchivedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CapabilitiesJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Evidence")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirmwareRevision")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("HeartRateDeviceFamily")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("HeartRateDeviceKind")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("IdentityFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .IsFixedLength();

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastVerifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProtocolId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TelemetryMode")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IdentityFingerprint");

                    b.HasIndex("Role")
                        .IsUnique()
                        .HasFilter("\"Role\" = 'Treadmill' AND \"IsArchived\" = 0");

                    b.HasIndex("Role", "DeviceId")
                        .IsUnique()
                        .HasFilter("\"IsArchived\" = 0");

                    b.ToTable("DeviceEnrollments", null, t =>
                        {
                            t.HasCheckConstraint("CK_DeviceEnrollments_Archive", "(\"IsArchived\" = 0 AND \"ArchivedAtUtc\" IS NULL) OR (\"IsArchived\" = 1 AND \"ArchivedAtUtc\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_DeviceEnrollments_DeviceId", "length(\"DeviceId\") > 0");

                            t.HasCheckConstraint("CK_DeviceEnrollments_Fingerprint", "length(\"IdentityFingerprint\") = 64");

                            t.HasCheckConstraint("CK_DeviceEnrollments_Protocol", "length(\"ProtocolId\") > 0");

                            t.HasCheckConstraint("CK_DeviceEnrollments_Role", "\"Role\" IN ('Treadmill', 'HeartRate')");

                            t.HasCheckConstraint("CK_DeviceEnrollments_TreadmillSettings", "(\"Role\" = 'Treadmill' AND \"TelemetryMode\" IS NOT NULL AND \"CapabilitiesJson\" IS NOT NULL) OR (\"Role\" = 'HeartRate' AND \"TelemetryMode\" IS NULL AND \"CapabilitiesJson\" IS NULL)");

                            t.HasCheckConstraint("CK_DeviceEnrollments_Version", "\"Version\" > 0");
                        });
                });

            modelBuilder.Entity("TreadmillRunner.Infrastructure.Persistence.HeartRateDeviceAssignmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutoConnect")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeviceEnrollmentId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPreferred")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeviceEnrollmentId");

                    b.HasIndex("UserProfileId")
                        .IsUnique()
                        .HasFilter("\"IsPreferred\" = 1");

                    b.HasIndex("UserProfileId", "DeviceEnrollmentId")
                        .IsUnique();

                    b.ToTable("HeartRateDeviceAssignments", null, t =>
                        {
                            t.HasCheckConstraint("CK_HeartRateDeviceAssignments_Priority", "\"Priority\" >= 0 AND \"Priority\" <= 99");

                            t.HasCheckConstraint("CK_HeartRateDeviceAssignments_Version", "\"Version\" > 0");
                        });
                });

            modelBuilder.Entity("TreadmillRunner.Infrastructure.Persistence.HeartRateZoneEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<ushort>("MaximumBpm")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("MinimumBpm")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId", "Number")
                        .IsUnique();

                    b.ToTable("HeartRateZones", null, t =>
                        {
                            t.HasCheckConstraint("CK_HeartRateZones_Number", "\"Number\" > 0");

                            t.HasCheckConstraint("CK_HeartRateZones_Range", "\"MinimumBpm\" <= \"MaximumBpm\"");
                        });
                });

            modelBuilder.Entity("TreadmillRunner.Infrastructure.Persistence.ImportAuditEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ImportedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .IsFixedLength();

                    b.Property<Guid?>("UserProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("WarningSummaryJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkoutRevisionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.HasIndex("WorkoutId");

                    b.HasIndex("WorkoutRevisionId");

                    b.HasIndex("Format", "SourceSha256");

                    b.ToTable("ImportAudits", (string)null);
                });

            modelBuilder.Entity("TreadmillRunner.Infrastructure.Persistence.OperationReceiptEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClientOperationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("OutcomeJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .IsFixedLength();

                    b.Property<int>("StatusCode")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClientOperationId")
                        .IsUnique();

                    b.ToTable("OperationReceipts", (string)null);
                });

            modelBuilder.Entity("TreadmillRunner.Infrastructure.Persistence.SessionEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkoutSessionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutSessionId", "OccurredAtUtc");

                    b.ToTable("SessionEvents", null, t =>
                        {
                            t.HasCheckConstraint("CK_SessionEvents_Kind", "length(\"Kind\") > 0");
                        });
                });

            modelBuilder.Entity("TreadmillRunner.Infrastructure.Persistence.SessionSampleEntity", b =>
                {
                    b.Property<Guid>("WorkoutSessionId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CapturedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<double>("DistanceKilometers")
                        .HasColumnType("REAL");

                    b.Property<double>("ElapsedMilliseconds")
                        .HasColumnType("REAL");

                    b.Property<double>("EstimatedCalories")
                        .HasColumnType("REAL");

                    b.Property<ushort?>("HeartRateBpm")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MeasuredInclinePercent")
                        .HasColumnType("REAL");

                    b.Property<double>("MeasuredSpeedKph")
                        .HasColumnType("REAL");

                    b.Property<string>("MetricAlgorithmVersion")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<double?>("PlannedInclinePercent")
                        .HasColumnType("REAL");

                    b.Property<double?>("PlannedSpeedKph")
                        .HasColumnType("REAL");

                    b.Property<double>("RequestedInclinePercent")
                        .HasColumnType("REAL");

                    b.Property<double>("RequestedSpeedKph")
                        .HasColumnType("REAL");

                    b.Property<double>("TelemetryAgeMilliseconds")
                        .HasColumnType("REAL");

                    b.HasKey("WorkoutSessionId", "Sequence");

                    b.HasIndex("WorkoutSessionId", "CapturedAtUtc");

                    b.ToTable("SessionSamples", null, t =>
                        {
                            t.HasCheckConstraint("CK_SessionSamples_Calories", "\"EstimatedCalories\" >= 0");

                            t.HasCheckConstraint("CK_SessionSamples_Distance", "\"DistanceKilometers\" >= 0");

                            t.HasCheckConstraint("CK_SessionSamples_Elapsed", "\"ElapsedMilliseconds\" >= 0");

                            t.HasCheckConstraint("CK_SessionSamples_Sequence", "\"Sequence\" >= 0");

                            t.HasCheckConstraint("CK_SessionSamples_Speeds", "(\"PlannedSpeedKph\" IS NULL OR \"PlannedSpeedKph\" >= 0) AND \"RequestedSpeedKph\" >= 0 AND \"MeasuredSpeedKph\" >= 0");

                            t.HasCheckConstraint("CK_SessionSamples_TelemetryAge", "\"TelemetryAgeMilliseconds\" >= 0");
                        });
                });

            modelBuilder.Entity("TreadmillRunner.Infrastructure.Persistence.TrainingDaySelectionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CalendarSeriesId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("LocalDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("SelectedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkoutRevisionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CalendarSeriesId");

                    b.HasIndex("WorkoutRevisionId");

                    b.HasIndex("UserProfileId", "LocalDate")
                        .IsUnique();

                    b.ToTable("TrainingDaySelections", (string)null);
                });

            modelBuilder.Entity("TreadmillRunner.Infrastructure.Persistence.UserProfileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ArchivedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("HeartRateDecreaseCooldownSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<double>("HeartRateDecreaseStepKph")
                        .HasColumnType("REAL");

                    b.Property<int>("HeartRateIncreaseCooldownSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<double>("HeartRateIncreaseStepKph")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<ushort?>("MaximumHeartRateBpm")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("MaximumSpeedKph")
                        .HasColumnType("REAL");

                    b.Property<string>("NormalizedDisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("UnitSystem")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<double>("WeightKilograms")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedDisplayName")
                        .IsUnique();

                    b.ToTable("UserProfiles", null, t =>
                        {
                            t.HasCheckConstraint("CK_UserProfiles_Archive", "(\"IsArchived\" = 0 AND \"ArchivedAtUtc\" IS NULL) OR (\"IsArchived\" = 1 AND \"ArchivedAtUtc\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_UserProfiles_DisplayName", "length(\"DisplayName\") > 0");

                            t.HasCheckConstraint("CK_UserProfiles_HrDecreaseCooldown", "\"HeartRateDecreaseCooldownSeconds\" >= 5 AND \"HeartRateDecreaseCooldownSeconds\" <= 120");

                            t.HasCheckConstraint("CK_UserProfiles_HrDecreaseStep", "\"HeartRateDecreaseStepKph\" >= 0.1 AND \"HeartRateDecreaseStepKph\" <= 1.0");

                            t.HasCheckConstraint("CK_UserProfiles_HrIncreaseCooldown", "\"HeartRateIncreaseCooldownSeconds\" >= 15 AND \"HeartRateIncreaseCooldownSeconds\" <= 180");

                            t.HasCheckConstraint("CK_UserProfiles_HrIncreaseStep", "\"HeartRateIncreaseStepKph\" >= 0.1 AND \"HeartRateIncreaseStepKph\" <= 0.5");

                            t.HasCheckConstraint("CK_UserProfiles_MaximumHeartRate", "\"MaximumHeartRateBpm\" IS NULL OR \"MaximumHeartRateBpm\" > 0");

                            t.HasCheckConstraint("CK_UserProfiles_MaximumSpeed", "\"MaximumSpeedKph\" IS NULL OR \"MaximumSpeedKph\" > 0");

                            t.HasCheckConstraint("CK_UserProfiles_Version", "\"Version\" > 0");

                            t.HasCheckConstraint("CK_UserProfiles_Weight", "\"WeightKilograms\" > 0");
                        });
                });

            modelBuilder.Entity("TreadmillRunner.Infrastructure.Persistence.WorkoutEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Workouts", null, t =>
                        {
                            t.HasCheckConstraint("CK_Workouts_Kind", "\"Kind\" IN ('Structured', 'ManualTemplate')");

                            t.HasCheckConstraint("CK_Workouts_Name", "length(\"Name\") > 0");
                        });
                });

            modelBuilder.Entity("TreadmillRunner.Infrastructure.Persistence.WorkoutProgramEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("WorkoutPrograms", (string)null);
                });

            modelBuilder.Entity("TreadmillRunner.Infrastructure.Persistence.WorkoutProgramItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WorkoutProgramRevisionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkoutRevisionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutRevisionId");

                    b.HasIndex("WorkoutProgramRevisionId", "Position")
                        .IsUnique();

                    b.ToTable("WorkoutProgramItems", null, t =>
                        {
                            t.HasCheckConstraint("CK_WorkoutProgramItems_Position", "\"Position\" > 0");
                        });
                });

            modelBuilder.Entity("TreadmillRunner.Infrastructure.Persistence.WorkoutProgramRevisionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WorkoutProgramId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutProgramId", "ContentSha256")
                        .IsUnique();

                    b.HasIndex("WorkoutProgramId", "RevisionNumber")
                        .IsUnique();

                    b.ToTable("WorkoutProgramRevisions", null, t =>
                        {
                            t.HasCheckConstraint("CK_WorkoutProgramRevisions_Category", "length(\"Category\") > 0");

                            t.HasCheckConstraint("CK_WorkoutProgramRevisions_Hash", "length(\"ContentSha256\") = 64");

                            t.HasCheckConstraint("CK_WorkoutProgramRevisions_Name", "length(\"Name\") > 0");

                            t.HasCheckConstraint("CK_WorkoutProgramRevisions_Number", "\"RevisionNumber\" > 0");
                        });
                });

            modelBuilder.Entity("TreadmillRunner.Infrastructure.Persistence.WorkoutProgramRunEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("EndedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WorkoutProgramRevisionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId")
                        .IsUnique()
                        .HasFilter("\"Status\" = 'Active'");

                    b.HasIndex("WorkoutProgramRevisionId");

                    b.HasIndex("UserProfileId", "StartedAtUtc");

                    b.ToTable("WorkoutProgramRuns", null, t =>
                        {
                            t.HasCheckConstraint("CK_WorkoutProgramRuns_Status", "\"Status\" IN ('Active', 'Completed', 'Abandoned')");

                            t.HasCheckConstraint("CK_WorkoutProgramRuns_Version", "\"Version\" > 0");
                        });
                });

            modelBuilder.Entity("TreadmillRunner.Infrastructure.Persistence.WorkoutRevisionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefinitionJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutId", "ContentSha256")
                        .IsUnique();

                    b.HasIndex("WorkoutId", "RevisionNumber")
                        .IsUnique();

                    b.ToTable("WorkoutRevisions", null, t =>
                        {
                            t.HasCheckConstraint("CK_WorkoutRevisions_Hash", "length(\"ContentSha256\") = 64");

                            t.HasCheckConstraint("CK_WorkoutRevisions_Json", "length(\"DefinitionJson\") > 0");

                            t.HasCheckConstraint("CK_WorkoutRevisions_Number", "\"RevisionNumber\" > 0");
                        });
                });

            modelBuilder.Entity("TreadmillRunner.Infrastructure.Persistence.WorkoutSessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ArmedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<double?>("AverageHeartRateBpm")
                        .HasColumnType("REAL");

                    b.Property<double>("AverageInclinePercent")
                        .HasColumnType("REAL");

                    b.Property<double>("AverageSpeedKph")
                        .HasColumnType("REAL");

                    b.Property<string>("ControllerConfigurationJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DebriefNote")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DebriefUpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<double>("DistanceKilometers")
                        .HasColumnType("REAL");

                    b.Property<double>("DurationSeconds")
                        .HasColumnType("REAL");

                    b.Property<DateTimeOffset?>("EndedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<double>("EstimatedCalories")
                        .HasColumnType("REAL");

                    b.Property<ushort?>("MaximumHeartRateBpm")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MetricAlgorithmVersion")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PerceivedExertion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SelectionSource")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserProfileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("WorkoutProgramItemId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("WorkoutProgramRunId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkoutRevisionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkoutTitle")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("State");

                    b.HasIndex("WorkoutProgramItemId");

                    b.HasIndex("WorkoutRevisionId");

                    b.HasIndex("UserProfileId", "ArmedAtUtc");

                    b.HasIndex("WorkoutProgramRunId", "WorkoutProgramItemId")
                        .IsUnique()
                        .HasFilter("\"State\" = 'Completed' AND \"WorkoutProgramRunId\" IS NOT NULL");

                    b.ToTable("WorkoutSessions", null, t =>
                        {
                            t.HasCheckConstraint("CK_WorkoutSessions_Calories", "\"EstimatedCalories\" >= 0");

                            t.HasCheckConstraint("CK_WorkoutSessions_Distance", "\"DistanceKilometers\" >= 0");

                            t.HasCheckConstraint("CK_WorkoutSessions_Duration", "\"DurationSeconds\" >= 0");

                            t.HasCheckConstraint("CK_WorkoutSessions_Rpe", "\"PerceivedExertion\" IS NULL OR (\"PerceivedExertion\" >= 1 AND \"PerceivedExertion\" <= 10)");

                            t.HasCheckConstraint("CK_WorkoutSessions_State", "length(\"State\") > 0");
                        });
                });

            modelBuilder.Entity("TreadmillRunner.Infrastructure.Persistence.CalendarExceptionEntity", b =>
                {
                    b.HasOne("TreadmillRunner.Infrastructure.Persistence.CalendarSeriesEntity", "CalendarSeries")
                        .WithMany("Exceptions")
                        .HasForeignKey("CalendarSeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CalendarSeries");
                });

            modelBuilder.Entity("TreadmillRunner.Infrastructure.Persistence.CalendarExceptionOptionEntity", b =>
                {
                    b.HasOne("TreadmillRunner.Infrastructure.Persistence.CalendarExceptionEntity", "CalendarException")
                        .WithMany("Options")
                        .HasForeignKey("CalendarExceptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TreadmillRunner.Infrastructure.Persistence.WorkoutRevisionEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkoutRevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CalendarException");
                });

            modelBuilder.Entity("TreadmillRunner.Infrastructure.Persistence.CalendarSeriesEntity", b =>
                {
                    b.HasOne("TreadmillRunner.Infrastructure.Persistence.UserProfileEntity", null)
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TreadmillRunner.Infrastructure.Persistence.CalendarSeriesOptionEntity", b =>
                {
                    b.HasOne("TreadmillRunner.Infrastructure.Persistence.CalendarSeriesEntity", "CalendarSeries")
                        .WithMany("Options")
                        .HasForeignKey("CalendarSeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TreadmillRunner.Infrastructure.Persistence.WorkoutRevisionEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkoutRevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CalendarSeries");
                });

            modelBuilder.Entity("TreadmillRunner.Infrastructure.Persistence.HeartRateDeviceAssignmentEntity", b =>
                {
                    b.HasOne("TreadmillRunner.Infrastructure.Persistence.DeviceEnrollmentEntity", "DeviceEnrollment")
                        .WithMany()
                        .HasForeignKey("DeviceEnrollmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TreadmillRunner.Infrastructure.Persistence.UserProfileEntity", "UserProfile")
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DeviceEnrollment");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("TreadmillRunner.Infrastructure.Persistence.HeartRateZoneEntity", b =>
                {
                    b.HasOne("TreadmillRunner.Infrastructure.Persistence.UserProfileEntity", "UserProfile")
                        .WithMany("HeartRateZones")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("TreadmillRunner.Infrastructure.Persistence.ImportAuditEntity", b =>
                {
                    b.HasOne("TreadmillRunner.Infrastructure.Persistence.UserProfileEntity", null)
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TreadmillRunner.Infrastructure.Persistence.WorkoutEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TreadmillRunner.Infrastructure.Persistence.WorkoutRevisionEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkoutRevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TreadmillRunner.Infrastructure.Persistence.SessionEventEntity", b =>
                {
                    b.HasOne("TreadmillRunner.Infrastructure.Persistence.WorkoutSessionEntity", "WorkoutSession")
                        .WithMany("Events")
                        .HasForeignKey("WorkoutSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutSession");
                });

            modelBuilder.Entity("TreadmillRunner.Infrastructure.Persistence.SessionSampleEntity", b =>
                {
                    b.HasOne("TreadmillRunner.Infrastructure.Persistence.WorkoutSessionEntity", "WorkoutSession")
                        .WithMany("Samples")
                        .HasForeignKey("WorkoutSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutSession");
                });

            modelBuilder.Entity("TreadmillRunner.Infrastructure.Persistence.TrainingDaySelectionEntity", b =>
                {
                    b.HasOne("TreadmillRunner.Infrastructure.Persistence.CalendarSeriesEntity", null)
                        .WithMany()
                        .HasForeignKey("CalendarSeriesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TreadmillRunner.Infrastructure.Persistence.UserProfileEntity", null)
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TreadmillRunner.Infrastructure.Persistence.WorkoutRevisionEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkoutRevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TreadmillRunner.Infrastructure.Persistence.WorkoutProgramItemEntity", b =>
                {
                    b.HasOne("TreadmillRunner.Infrastructure.Persistence.WorkoutProgramRevisionEntity", "WorkoutProgramRevision")
                        .WithMany("Items")
                        .HasForeignKey("WorkoutProgramRevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TreadmillRunner.Infrastructure.Persistence.WorkoutRevisionEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkoutRevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("WorkoutProgramRevision");
                });

            modelBuilder.Entity("TreadmillRunner.Infrastructure.Persistence.WorkoutProgramRevisionEntity", b =>
                {
                    b.HasOne("TreadmillRunner.Infrastructure.Persistence.WorkoutProgramEntity", "WorkoutProgram")
                        .WithMany("Revisions")
                        .HasForeignKey("WorkoutProgramId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("WorkoutProgram");
                });

            modelBuilder.Entity("TreadmillRunner.Infrastructure.Persistence.WorkoutProgramRunEntity", b =>
                {
                    b.HasOne("TreadmillRunner.Infrastructure.Persistence.UserProfileEntity", null)
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TreadmillRunner.Infrastructure.Persistence.WorkoutProgramRevisionEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkoutProgramRevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TreadmillRunner.Infrastructure.Persistence.WorkoutRevisionEntity", b =>
                {
                    b.HasOne("TreadmillRunner.Infrastructure.Persistence.WorkoutEntity", "Workout")
                        .WithMany("Revisions")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("TreadmillRunner.Infrastructure.Persistence.WorkoutSessionEntity", b =>
                {
                    b.HasOne("TreadmillRunner.Infrastructure.Persistence.UserProfileEntity", null)
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TreadmillRunner.Infrastructure.Persistence.WorkoutProgramItemEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkoutProgramItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TreadmillRunner.Infrastructure.Persistence.WorkoutProgramRunEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkoutProgramRunId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TreadmillRunner.Infrastructure.Persistence.WorkoutRevisionEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkoutRevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TreadmillRunner.Infrastructure.Persistence.CalendarExceptionEntity", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("TreadmillRunner.Infrastructure.Persistence.CalendarSeriesEntity", b =>
                {
                    b.Navigation("Exceptions");

                    b.Navigation("Options");
                });

            modelBuilder.Entity("TreadmillRunner.Infrastructure.Persistence.UserProfileEntity", b =>
                {
                    b.Navigation("HeartRateZones");
                });

            modelBuilder.Entity("TreadmillRunner.Infrastructure.Persistence.WorkoutEntity", b =>
                {
                    b.Navigation("Revisions");
                });

            modelBuilder.Entity("TreadmillRunner.Infrastructure.Persistence.WorkoutProgramEntity", b =>
                {
                    b.Navigation("Revisions");
                });

            modelBuilder.Entity("TreadmillRunner.Infrastructure.Persistence.WorkoutProgramRevisionEntity", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("TreadmillRunner.Infrastructure.Persistence.WorkoutSessionEntity", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Samples");
                });
#pragma warning restore 612, 618
        }
    }
}
