// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TreadmillRunner.Infrastructure.Persistence;

#nullable disable

namespace TreadmillRunner.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TreadmillRunnerDbContext))]
    [Migration("20260801234729_InitialPersistence")]
    partial class InitialPersistence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("TreadmillRunner.Infrastructure.Persistence.CalendarExceptionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CalendarSeriesId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("LocalDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CalendarSeriesId", "LocalDate")
                        .IsUnique();

                    b.ToTable("CalendarExceptions", (string)null);
                });

            modelBuilder.Entity("TreadmillRunner.Infrastructure.Persistence.CalendarExceptionOptionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CalendarExceptionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WorkoutRevisionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutRevisionId");

                    b.HasIndex("CalendarExceptionId", "DisplayOrder")
                        .IsUnique();

                    b.ToTable("CalendarExceptionOptions", (string)null);
                });

            modelBuilder.Entity("TreadmillRunner.Infrastructure.Persistence.CalendarSeriesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("IntervalWeeks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<int>("WeekdayMask")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("CalendarSeries", null, t =>
                        {
                            t.HasCheckConstraint("CK_CalendarSeries_DateRange", "\"EndDate\" IS NULL OR \"EndDate\" >= \"StartDate\"");

                            t.HasCheckConstraint("CK_CalendarSeries_Interval", "\"IntervalWeeks\" > 0");

                            t.HasCheckConstraint("CK_CalendarSeries_Version", "\"Version\" > 0");

                            t.HasCheckConstraint("CK_CalendarSeries_Weekdays", "\"WeekdayMask\" > 0 AND \"WeekdayMask\" <= 127");
                        });
                });

            modelBuilder.Entity("TreadmillRunner.Infrastructure.Persistence.CalendarSeriesOptionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CalendarSeriesId")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WorkoutRevisionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutRevisionId");

                    b.HasIndex("CalendarSeriesId", "DisplayOrder")
                        .IsUnique();

                    b.ToTable("CalendarSeriesOptions", (string)null);
                });

            modelBuilder.Entity("TreadmillRunner.Infrastructure.Persistence.HeartRateZoneEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<ushort>("MaximumBpm")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("MinimumBpm")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId", "Number")
                        .IsUnique();

                    b.ToTable("HeartRateZones", null, t =>
                        {
                            t.HasCheckConstraint("CK_HeartRateZones_Number", "\"Number\" > 0");

                            t.HasCheckConstraint("CK_HeartRateZones_Range", "\"MinimumBpm\" <= \"MaximumBpm\"");
                        });
                });

            modelBuilder.Entity("TreadmillRunner.Infrastructure.Persistence.ImportAuditEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ImportedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .IsFixedLength();

                    b.Property<Guid?>("UserProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("WarningSummaryJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkoutRevisionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.HasIndex("WorkoutId");

                    b.HasIndex("WorkoutRevisionId");

                    b.HasIndex("Format", "SourceSha256");

                    b.ToTable("ImportAudits", (string)null);
                });

            modelBuilder.Entity("TreadmillRunner.Infrastructure.Persistence.OperationReceiptEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClientOperationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .IsFixedLength()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("OutcomeJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StatusCode")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClientOperationId")
                        .IsUnique();

                    b.ToTable("OperationReceipts", (string)null);
                });

            modelBuilder.Entity("TreadmillRunner.Infrastructure.Persistence.TrainingDaySelectionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CalendarSeriesId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("LocalDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("SelectedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkoutRevisionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CalendarSeriesId");

                    b.HasIndex("WorkoutRevisionId");

                    b.HasIndex("UserProfileId", "LocalDate")
                        .IsUnique();

                    b.ToTable("TrainingDaySelections", (string)null);
                });

            modelBuilder.Entity("TreadmillRunner.Infrastructure.Persistence.UserProfileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ArchivedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<ushort?>("MaximumHeartRateBpm")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("MaximumSpeedKph")
                        .HasColumnType("REAL");

                    b.Property<string>("NormalizedDisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("UnitSystem")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<double>("WeightKilograms")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedDisplayName")
                        .IsUnique();

                    b.ToTable("UserProfiles", null, t =>
                        {
                            t.HasCheckConstraint("CK_UserProfiles_Archive", "(\"IsArchived\" = 0 AND \"ArchivedAtUtc\" IS NULL) OR (\"IsArchived\" = 1 AND \"ArchivedAtUtc\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_UserProfiles_DisplayName", "length(\"DisplayName\") > 0");

                            t.HasCheckConstraint("CK_UserProfiles_MaximumHeartRate", "\"MaximumHeartRateBpm\" IS NULL OR \"MaximumHeartRateBpm\" > 0");

                            t.HasCheckConstraint("CK_UserProfiles_MaximumSpeed", "\"MaximumSpeedKph\" IS NULL OR \"MaximumSpeedKph\" > 0");

                            t.HasCheckConstraint("CK_UserProfiles_Version", "\"Version\" > 0");

                            t.HasCheckConstraint("CK_UserProfiles_Weight", "\"WeightKilograms\" > 0");
                        });
                });

            modelBuilder.Entity("TreadmillRunner.Infrastructure.Persistence.WorkoutEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Workouts", null, t =>
                        {
                            t.HasCheckConstraint("CK_Workouts_Name", "length(\"Name\") > 0");
                        });
                });

            modelBuilder.Entity("TreadmillRunner.Infrastructure.Persistence.WorkoutRevisionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefinitionJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutId", "ContentSha256")
                        .IsUnique();

                    b.HasIndex("WorkoutId", "RevisionNumber")
                        .IsUnique();

                    b.ToTable("WorkoutRevisions", null, t =>
                        {
                            t.HasCheckConstraint("CK_WorkoutRevisions_Hash", "length(\"ContentSha256\") = 64");

                            t.HasCheckConstraint("CK_WorkoutRevisions_Json", "length(\"DefinitionJson\") > 0");

                            t.HasCheckConstraint("CK_WorkoutRevisions_Number", "\"RevisionNumber\" > 0");
                        });
                });

            modelBuilder.Entity("TreadmillRunner.Infrastructure.Persistence.CalendarExceptionEntity", b =>
                {
                    b.HasOne("TreadmillRunner.Infrastructure.Persistence.CalendarSeriesEntity", "CalendarSeries")
                        .WithMany("Exceptions")
                        .HasForeignKey("CalendarSeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CalendarSeries");
                });

            modelBuilder.Entity("TreadmillRunner.Infrastructure.Persistence.CalendarExceptionOptionEntity", b =>
                {
                    b.HasOne("TreadmillRunner.Infrastructure.Persistence.CalendarExceptionEntity", "CalendarException")
                        .WithMany("Options")
                        .HasForeignKey("CalendarExceptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TreadmillRunner.Infrastructure.Persistence.WorkoutRevisionEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkoutRevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CalendarException");
                });

            modelBuilder.Entity("TreadmillRunner.Infrastructure.Persistence.CalendarSeriesEntity", b =>
                {
                    b.HasOne("TreadmillRunner.Infrastructure.Persistence.UserProfileEntity", null)
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TreadmillRunner.Infrastructure.Persistence.CalendarSeriesOptionEntity", b =>
                {
                    b.HasOne("TreadmillRunner.Infrastructure.Persistence.CalendarSeriesEntity", "CalendarSeries")
                        .WithMany("Options")
                        .HasForeignKey("CalendarSeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TreadmillRunner.Infrastructure.Persistence.WorkoutRevisionEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkoutRevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CalendarSeries");
                });

            modelBuilder.Entity("TreadmillRunner.Infrastructure.Persistence.HeartRateZoneEntity", b =>
                {
                    b.HasOne("TreadmillRunner.Infrastructure.Persistence.UserProfileEntity", "UserProfile")
                        .WithMany("HeartRateZones")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("TreadmillRunner.Infrastructure.Persistence.ImportAuditEntity", b =>
                {
                    b.HasOne("TreadmillRunner.Infrastructure.Persistence.UserProfileEntity", null)
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TreadmillRunner.Infrastructure.Persistence.WorkoutEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TreadmillRunner.Infrastructure.Persistence.WorkoutRevisionEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkoutRevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TreadmillRunner.Infrastructure.Persistence.TrainingDaySelectionEntity", b =>
                {
                    b.HasOne("TreadmillRunner.Infrastructure.Persistence.CalendarSeriesEntity", null)
                        .WithMany()
                        .HasForeignKey("CalendarSeriesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TreadmillRunner.Infrastructure.Persistence.UserProfileEntity", null)
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TreadmillRunner.Infrastructure.Persistence.WorkoutRevisionEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkoutRevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TreadmillRunner.Infrastructure.Persistence.WorkoutRevisionEntity", b =>
                {
                    b.HasOne("TreadmillRunner.Infrastructure.Persistence.WorkoutEntity", "Workout")
                        .WithMany("Revisions")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("TreadmillRunner.Infrastructure.Persistence.CalendarExceptionEntity", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("TreadmillRunner.Infrastructure.Persistence.CalendarSeriesEntity", b =>
                {
                    b.Navigation("Exceptions");

                    b.Navigation("Options");
                });

            modelBuilder.Entity("TreadmillRunner.Infrastructure.Persistence.UserProfileEntity", b =>
                {
                    b.Navigation("HeartRateZones");
                });

            modelBuilder.Entity("TreadmillRunner.Infrastructure.Persistence.WorkoutEntity", b =>
                {
                    b.Navigation("Revisions");
                });
#pragma warning restore 612, 618
        }
    }
}
