param(
    [Parameter(Mandatory = $true)]
    [string] $SourceRoot,

    [string] $OutputPath = (Join-Path $PSScriptRoot '..\src\TreadmillRunner.Core\Workouts\WalkingPadDistancePlanData.g.cs')
)

$ErrorActionPreference = 'Stop'
$resolvedSource = [System.IO.Path]::GetFullPath($SourceRoot)
$indexPath = Join-Path $resolvedSource 'workout_index.csv'
if (-not (Test-Path -LiteralPath $indexPath -PathType Leaf)) {
    throw "Workout index is missing: $indexPath"
}

$rows = Import-Csv -LiteralPath $indexPath
$slots = foreach ($group in ($rows | Group-Object { 'W{0:D2}D{1}' -f [int]$_.week, [int]$_.session } | Sort-Object { [int]$_.Group[0].week }, { [int]$_.Group[0].session })) {
    $variants = foreach ($entry in $group.Group) {
        $xmlPath = Join-Path $resolvedSource $entry.walkingpad_file
        if (-not (Test-Path -LiteralPath $xmlPath -PathType Leaf)) {
            throw "Indexed workout is missing: $xmlPath"
        }
        [xml] $document = Get-Content -Raw -LiteralPath $xmlPath
        $workoutRows = foreach ($row in $document.rows.row) {
            [ordered]@{
                durationSeconds = [int][TimeSpan]::ParseExact([string]$row.duration, 'hh\:mm\:ss', [Globalization.CultureInfo]::InvariantCulture).TotalSeconds
                speed = [double]::Parse([string]$row.speed, [Globalization.CultureInfo]::InvariantCulture)
                incline = [double]::Parse([string]$row.inclination, [Globalization.CultureInfo]::InvariantCulture)
                forceSpeed = ([string]$row.forcespeed -ne '0')
                zone = [int]$row.zonehr
                heartRateMinimum = [int]$row.hrmin
                heartRateMaximum = [int]$row.hrmax
                minimumSpeed = if ($null -eq $row.minspeed -or [string]$row.minspeed -eq '') { 0.0 } else { [double]::Parse([string]$row.minspeed, [Globalization.CultureInfo]::InvariantCulture) }
                maximumSpeed = if ($null -eq $row.maxspeed -or [string]$row.maxspeed -eq '') { 0.0 } else { [double]::Parse([string]$row.maxspeed, [Globalization.CultureInfo]::InvariantCulture) }
            }
        }
        [ordered]@{
            id = $entry.session_id
            variant = $entry.variant
            title = $entry.title
            selectionRule = $entry.selection_rule
            rows = @($workoutRows)
        }
    }
    [ordered]@{
        slot = $group.Name
        week = [int]$group.Group[0].week
        session = [int]$group.Group[0].session
        variants = @($variants)
    }
}

$json = ConvertTo-Json @($slots) -Depth 8 -Compress
$utf8 = [Text.Encoding]::UTF8.GetBytes($json)
$digest = [Convert]::ToHexStringLower([Security.Cryptography.SHA256]::HashData($utf8))
$memory = [IO.MemoryStream]::new()
$gzip = [IO.Compression.GZipStream]::new($memory, [IO.Compression.CompressionLevel]::SmallestSize, $true)
$gzip.Write($utf8, 0, $utf8.Length)
$gzip.Dispose()
$base64 = [Convert]::ToBase64String($memory.ToArray())
$memory.Dispose()

$source = @"
// <auto-generated />
// Provenance: owner-provided WalkingPad/QDomyos 58-week 5K-to-10K source snapshot.
// Inputs: workout_index.csv plus each indexed QDomyos v4 XML file.
// Regenerate: pwsh -File eng/generate-walkingpad-plan.ps1 -SourceRoot <reviewed-source-directory>
namespace TreadmillRunner.Core.Workouts;

internal static class WalkingPadDistancePlanData
{
  internal const string SourceProvenance = "Owner-provided WalkingPad/QDomyos 58-week 5K-to-10K source snapshot";
  internal const string GeneratorPath = "eng/generate-walkingpad-plan.ps1";
  internal const string ContentSha256 = "$digest";
  internal const string GzipBase64 = "$base64";
}
"@

$resolvedOutput = [System.IO.Path]::GetFullPath($OutputPath)
[IO.Directory]::CreateDirectory([IO.Path]::GetDirectoryName($resolvedOutput)) | Out-Null
[IO.File]::WriteAllText($resolvedOutput, $source, [Text.UTF8Encoding]::new($false))
Write-Output "Generated $resolvedOutput from $($rows.Count) indexed variants in $($slots.Count) slots (SHA-256 $digest)."
