<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoDefaultLaunchSettingsFile>true</NoDefaultLaunchSettingsFile>
    <StaticWebAssetProjectMode>Default</StaticWebAssetProjectMode>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <PublishTrimmed>true</PublishTrimmed>
    <WasmEnableHotReload>false</WasmEnableHotReload>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" />
  </ItemGroup>

  <ItemGroup>
    <BlazorWebAssemblyLazyLoad Include="Microsoft.AspNetCore.Connections.Abstractions.dll" />
    <BlazorWebAssemblyLazyLoad Include="Microsoft.AspNetCore.Http.Connections.Client.dll" />
    <BlazorWebAssemblyLazyLoad Include="Microsoft.AspNetCore.Http.Connections.Common.dll" />
    <BlazorWebAssemblyLazyLoad Include="Microsoft.AspNetCore.SignalR.Client.dll" />
    <BlazorWebAssemblyLazyLoad Include="Microsoft.AspNetCore.SignalR.Client.Core.dll" />
    <BlazorWebAssemblyLazyLoad Include="Microsoft.AspNetCore.SignalR.Common.dll" />
    <BlazorWebAssemblyLazyLoad Include="Microsoft.AspNetCore.SignalR.Protocols.Json.dll" />
    <BlazorWebAssemblyLazyLoad Include="Microsoft.Extensions.Features.dll" />
    <BlazorWebAssemblyLazyLoad Include="TreadmillRunner.Web.SignalR.dll" />
    <BlazorWebAssemblyLazyLoad Include="TreadmillRunner.Web.Operations.dll" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TreadmillRunner.Core\TreadmillRunner.Core.csproj" />
    <ProjectReference Include="..\TreadmillRunner.Web.SignalR\TreadmillRunner.Web.SignalR.csproj" />
    <ProjectReference Include="..\TreadmillRunner.Web.Runtime\TreadmillRunner.Web.Runtime.csproj" />
    <ProjectReference Include="..\TreadmillRunner.Web.Operations\TreadmillRunner.Web.Operations.csproj" />
  </ItemGroup>

  <ItemGroup>
    <TrimmerRootAssembly Include="TreadmillRunner.Web.SignalR" />
    <TrimmerRootAssembly Include="TreadmillRunner.Web.Operations" />
  </ItemGroup>

</Project>
