#!/usr/bin/env python3
"""Generated artifact helpers owned by skill-manager."""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

sys.dont_write_bytecode = True

from repo_support import repo_common as repo
from repo_support import repo_policy
import module_contract_v3

GENERATED_CLAUDE_HEADER = (
    "<!-- Generated by skill-manager repo_manager.py sync-claude-skills. "
    "Do not edit by hand. -->"
)
GENERATED_INSTRUCTION_HEADER = (
    "<!-- Generated from AGENTS.md by skill-manager repo_manager.py sync-instructions. "
    "Do not edit by hand. -->"
)
TOKEN_ESTIMATE_CHARS = 3.7


def normalized_instruction_source(source_text: str) -> str:
    return source_text.replace("\r\n", "\n").rstrip()


def generated_copilot_instructions(source_text: str) -> str:
    normalized = normalized_instruction_source(source_text)
    return (
        f"{GENERATED_INSTRUCTION_HEADER}\n\n"
        f"{normalized}\n"
    )


def generated_claude_project_instructions(source_text: str) -> str:
    _normalized = normalized_instruction_source(source_text)
    return (
        f"{GENERATED_INSTRUCTION_HEADER}\n\n"
        "# Claude Project Instructions\n\n"
        "These instructions import the canonical root `AGENTS.md` so Claude Code "
        "loads the current repository guidance at session start.\n\n"
        "@../AGENTS.md\n"
    )


def generated_gemini_instructions(source_text: str) -> str:
    _normalized = normalized_instruction_source(source_text)
    return (
        f"{GENERATED_INSTRUCTION_HEADER}\n\n"
        "# Gemini Project Instructions\n\n"
        "Import the canonical root `AGENTS.md` for Gemini CLI project context.\n\n"
        "@AGENTS.md\n"
    )


def generated_continue_rule(source_text: str) -> str:
    normalized = normalized_instruction_source(source_text)
    return (
        "---\n"
        "name: Repository Instructions\n"
        "alwaysApply: true\n"
        "---\n\n"
        f"{GENERATED_INSTRUCTION_HEADER}\n\n"
        "These instructions are generated from the canonical root `AGENTS.md`.\n\n"
        f"{normalized}\n"
    )


def generated_aider_config(source_text: str) -> str:
    _normalized = normalized_instruction_source(source_text)
    return (
        "# Generated from AGENTS.md by skill-manager repo_manager.py sync-instructions.\n"
        "# Do not edit by hand.\n"
        "read: AGENTS.md\n"
    )


def expected_instruction_adapters(root: Path, source_text: str) -> dict[Path, str]:
    return {
        root / ".github" / "copilot-instructions.md": generated_copilot_instructions(
            source_text
        ),
        root / ".claude" / "CLAUDE.md": generated_claude_project_instructions(
            source_text
        ),
        root / "GEMINI.md": generated_gemini_instructions(source_text),
        root / ".continue" / "rules" / "repository-instructions.md": generated_continue_rule(
            source_text
        ),
        root / ".aider.conf.yml": generated_aider_config(source_text),
    }


def sync_instructions(root: Path, check: bool) -> int:
    source = root / "AGENTS.md"
    if not source.exists():
        raise SystemExit(f"canonical instructions file not found: {source}")

    outputs = expected_instruction_adapters(root, source.read_text(encoding="utf-8"))
    if check:
        stale: list[Path] = []
        for target, expected in outputs.items():
            if not target.exists():
                stale.append(target)
                continue
            actual = target.read_text(encoding="utf-8").replace("\r\n", "\n")
            if actual != expected:
                stale.append(target)
        if stale:
            details = "\n".join(
                f"- {repo.relative(root, path)} is missing or stale." for path in stale
            )
            raise SystemExit(
                f"Generated project instructions are out of sync with AGENTS.md.\n"
                f"{details}\n"
                "Run: python -B .agents/manage.py sync-instructions"
            )
        print("Instruction adapters are in sync.", flush=True)
        return 0

    for target, expected in outputs.items():
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(expected, encoding="utf-8", newline="\n")
        print(f"Generated {repo.relative(root, target)} from AGENTS.md.")
    return 0


def sync_skill_routing(root: Path, check: bool, deep: bool = False) -> int:
    script = repo.skill_manager_script(root, "sync_skill_routing.py")
    command = repo.python_command(script, ["--root", str(root)])
    if check:
        command.append("--check")
    if deep:
        command.append("--deep")
    return subprocess.run(command, check=False, env=repo.child_env()).returncode


def sync_module_schema(root: Path, check: bool) -> int:
    """Generate the strict module schema from the authoritative Python contract."""

    target = root / ".agents" / "skills" / "skill-manager" / "assets" / "schemas" / "module.schema.json"
    expected = json.dumps(
        module_contract_v3.module_contract_schema(),
        ensure_ascii=False,
        indent=2,
        sort_keys=True,
    ) + "\n"
    if check:
        actual = target.read_text(encoding="utf-8").replace("\r\n", "\n") if target.exists() else ""
        if actual != expected:
            raise SystemExit(
                "Generated module schema is missing or stale.\n"
                "Run: python -B .agents/manage.py sync"
            )
        print("Generated module schema is in sync.", flush=True)
        return 0
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(expected, encoding="utf-8", newline="\n")
    print(f"Generated {repo.relative(root, target)}.")
    return 0


def sync_project_policy_schema(root: Path, check: bool) -> int:
    """Generate the strict project-policy schema from its runtime contract."""

    target = root / ".agents" / "skills" / "skill-manager" / "assets" / "schemas" / "project-policy.schema.json"
    expected = json.dumps(repo_policy.generated_schema(), ensure_ascii=False, indent=2, sort_keys=True) + "\n"
    actual = target.read_text(encoding="utf-8").replace("\r\n", "\n") if target.exists() else ""
    if check:
        if actual != expected:
            raise SystemExit("Generated project-policy schema is missing or stale.\nRun: python -B .agents/manage.py sync")
        print("Generated project-policy schema is in sync.", flush=True)
        return 0
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(expected, encoding="utf-8", newline="\n")
    print(f"Generated {repo.relative(root, target)}.")
    return 0


def validate_automations(root: Path) -> int:
    return repo.run_workflow_repo_manager(root, ["validate-automations", "--root", str(root)])


def sync_automation_routing(root: Path, check: bool) -> int:
    command = ["sync-automation-routing", "--root", str(root)]
    if check:
        command.append("--check")
    return repo.run_workflow_repo_manager(root, command)


def parse_skill_frontmatter(skill_file: Path) -> dict[str, str]:
    metadata: dict[str, str] = {}
    lines = skill_file.read_text(encoding="utf-8-sig").splitlines()
    if not lines or lines[0].strip() != "---":
        return metadata
    for line in lines[1:]:
        if line.strip() == "---":
            break
        if ":" not in line:
            continue
        key, value = line.split(":", 1)
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in {"'", '"'}:
            value = value[1:-1]
        metadata[key.strip()] = value
    return metadata


def generated_claude_adapter(root: Path, skill_dir: Path) -> str:
    metadata = parse_skill_frontmatter(skill_dir / "SKILL.md")
    name = metadata.get("name") or skill_dir.name
    description = metadata.get("description") or f"Use this generated adapter for {name}."
    canonical = f"../../../.agents/skills/{skill_dir.name}/SKILL.md"
    return (
        "---\n"
        f"name: {name}\n"
        f"description: {description}\n"
        "---\n\n"
        f"{GENERATED_CLAUDE_HEADER}\n\n"
        f"# {name}\n\n"
        "This is a generated Claude Code adapter. Read and follow "
        f"`{canonical}`; supporting docs and scripts remain under "
        f"`.agents/skills/{skill_dir.name}/`.\n"
    )


def is_generated_claude_adapter(content: str) -> bool:
    """Recognize only bounded generated wrappers, independent of marker line position."""

    normalized = content.replace("\r\n", "\n")
    prefix = normalized[:8192]
    return (
        GENERATED_CLAUDE_HEADER in prefix
        and "This is a generated Claude Code adapter. Read and follow " in prefix
    )


def expected_claude_adapters(root: Path) -> dict[Path, str]:
    return {
        root / ".claude" / "skills" / skill_dir.name / "SKILL.md": generated_claude_adapter(
            root, skill_dir
        )
        for skill_dir in repo.skill_directories(root / ".agents" / "skills")
    }


def estimated_tokens(text: str) -> int:
    return round(len(text) / TOKEN_ESTIMATE_CHARS)


def claude_adapter_budget_report(root: Path) -> dict[str, object]:
    threshold_tokens = repo_policy.int_value(root, "owner_defaults.skill_manager.claude_adapter.name_only_saved_tokens")
    threshold_skills = repo_policy.int_value(root, "owner_defaults.skill_manager.claude_adapter.name_only_skill_count")
    context_window = repo_policy.int_value(root, "owner_defaults.skill_manager.claude_adapter.context_window_tokens")
    rows: list[dict[str, object]] = []
    full_tokens = 0
    name_only_tokens = 0
    description_characters = 0
    stale: list[str] = []
    for skill_dir in repo.skill_directories(root / ".agents" / "skills"):
        metadata = parse_skill_frontmatter(skill_dir / "SKILL.md")
        name = metadata.get("name") or skill_dir.name
        description = metadata.get("description") or f"Use this generated adapter for {name}."
        full_text = f"- {name}: {description}\n"
        name_only_text = f"- {name}\n"
        full = estimated_tokens(full_text)
        name_only = estimated_tokens(name_only_text)
        saved = max(0, full - name_only)
        adapter_path = root / ".claude" / "skills" / skill_dir.name / "SKILL.md"
        expected = generated_claude_adapter(root, skill_dir)
        if not adapter_path.exists():
            stale.append(repo.relative(root, adapter_path))
        else:
            actual = adapter_path.read_text(encoding="utf-8").replace("\r\n", "\n")
            if actual != expected:
                stale.append(repo.relative(root, adapter_path))
        description_characters += len(description)
        full_tokens += full
        name_only_tokens += name_only
        rows.append(
            {
                "name": name,
                "path": repo.relative(root, adapter_path),
                "description_characters": len(description),
                "full_listing_estimated_tokens": full,
                "name_only_estimated_tokens": name_only,
                "estimated_saved_tokens": saved,
            }
        )
    saved_tokens = full_tokens - name_only_tokens
    worth_considering = (
        saved_tokens >= threshold_tokens
        or len(rows) >= threshold_skills
    )
    recommendation = (
        "consider opt-in name-only adapters with a retrieval fallback"
        if worth_considering
        else "keep normal generated adapters; savings are below the repo threshold"
    )
    status = "stale-adapters" if stale else "measured"
    return {
        "schema_version": 1,
        "tool": "skill-manager.claude-adapter-budget",
        "ok": not stale,
        "status": status,
        "summary": {
            "adapter_count": len(rows),
            "description_characters": description_characters,
            "full_listing_estimated_tokens": full_tokens,
            "name_only_estimated_tokens": name_only_tokens,
            "estimated_saved_tokens": saved_tokens,
            "saved_percent_of_context_window": round(saved_tokens / context_window * 100, 3),
            "worth_considering_name_only": worth_considering,
            "threshold_saved_tokens": threshold_tokens,
            "threshold_skill_count": threshold_skills,
            "context_window_tokens": context_window,
            "token_estimate": f"chars/{TOKEN_ESTIMATE_CHARS}",
        },
        "recommendation": recommendation,
        "top_descriptions": sorted(
            rows,
            key=lambda item: int(item.get("estimated_saved_tokens", 0) or 0),
            reverse=True,
        )[:10],
        "stale_adapters": stale,
        "next_command": "python -B .agents/manage.py sync-claude-skills" if stale else "",
    }


def summarize_claude_adapter_budget_report(
    report: dict[str, object], *, compact: bool = False
) -> dict[str, object]:
    output: dict[str, object] = {
        "schema_version": report.get("schema_version", 1),
        "tool": report.get("tool", "skill-manager.claude-adapter-budget"),
        "ok": bool(report.get("ok", False)),
        "status": report.get("status", ""),
        "summary": report.get("summary", {}),
        "recommendation": report.get("recommendation", ""),
        "next_command": report.get("next_command", ""),
    }
    if not compact:
        output["top_descriptions"] = report.get("top_descriptions", [])
        output["stale_adapters"] = report.get("stale_adapters", [])
    return output


def render_claude_adapter_budget(report: dict[str, object]) -> str:
    summary = report.get("summary") if isinstance(report.get("summary"), dict) else {}
    lines = [
        "# Claude Adapter Budget",
        "",
        f"- Status: {report.get('status')}",
        f"- Adapters: {summary.get('adapter_count', 0)}",
        f"- Full listing estimate: {summary.get('full_listing_estimated_tokens', 0)} tokens",
        f"- Name-only estimate: {summary.get('name_only_estimated_tokens', 0)} tokens",
        f"- Estimated saved: {summary.get('estimated_saved_tokens', 0)} tokens ({summary.get('saved_percent_of_200k', 0)}% of 200K)",
        f"- Recommendation: {report.get('recommendation')}",
    ]
    top = report.get("top_descriptions") if isinstance(report.get("top_descriptions"), list) else []
    if top:
        lines.extend(["", "## Largest Description Savings", ""])
        for row in top[:5]:
            if isinstance(row, dict):
                lines.append(
                    f"- `{row.get('name')}`: {row.get('estimated_saved_tokens', 0)} tokens "
                    f"from {row.get('description_characters', 0)} description chars"
                )
    stale = report.get("stale_adapters") if isinstance(report.get("stale_adapters"), list) else []
    if stale:
        lines.extend(["", "## Stale Adapters", ""])
        lines.extend(f"- `{item}`" for item in stale[:20])
        lines.append(f"- Fix: `{report.get('next_command')}`")
    return "\n".join(lines) + "\n"


def sync_claude_skills(root: Path, check: bool) -> int:
    outputs = expected_claude_adapters(root)
    stale: list[Path] = []
    obsolete: list[Path] = []
    for path, expected in outputs.items():
        if not path.exists():
            stale.append(path)
            continue
        actual = path.read_text(encoding="utf-8").replace("\r\n", "\n")
        if actual != expected:
            stale.append(path)

    claude_root = root / ".claude" / "skills"
    if claude_root.exists():
        expected_paths = {repo.norm_key(path) for path in outputs}
        for adapter in sorted(claude_root.glob("*/SKILL.md"), key=lambda item: item.as_posix()):
            if repo.norm_key(adapter) in expected_paths:
                continue
            content = adapter.read_text(encoding="utf-8", errors="replace")
            if is_generated_claude_adapter(content):
                obsolete.append(adapter)

    if check:
        if stale or obsolete:
            for path in stale:
                print(f"ERROR: {repo.relative(root, path)} is missing or stale.", file=sys.stderr)
            for path in obsolete:
                print(f"ERROR: {repo.relative(root, path)} is obsolete.", file=sys.stderr)
            print(
                "Run: python -B .agents/manage.py sync-claude-skills",
                file=sys.stderr,
            )
            return 1
        print("Claude skill adapters are in sync.")
        return 0

    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")
        print(f"Generated {repo.relative(root, path)}.")
    for path in obsolete:
        skill_dir = path.parent
        path.unlink()
        try:
            skill_dir.rmdir()
        except OSError:
            pass
        print(f"Removed obsolete generated adapter {repo.relative(root, path)}.")
    return 0


def sync_all(root: Path, check: bool) -> int:
    commands = [
        sync_instructions,
        sync_skill_routing,
        sync_module_schema,
        sync_project_policy_schema,
        sync_automation_routing,
        sync_claude_skills,
    ]
    for command in commands:
        status = command(root, check=check)
        if status != 0:
            return status
    return 0
